name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VITE_YOGA_DATA_URL: ${{ vars.VITE_YOGA_DATA_URL }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build project
        run: npm run build
        working-directory: ./frontend

      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: ./frontend/dist

  deploy:
    name: Deploy
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./dist
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.G_ACCESS_TOKEN }}
